### ISSUE TITLE
Base path of API

### ISSUE THREAD

**Issue by thboomsma** [DharanBro/hapi-sequelize-restify#14]
Where can we change the API base path to e.g. /api/v1 ?

**Comment by DharanBro** [comment]
@thboomsma At this moment base path support is not available. But we can add it as this could be really useful. Before implementing this I would like to know, how you would expect to use it?

**Comment by thboomsma** [comment]
Im almost sure that HAPI must have some setting for it somewhere, but im new to it so maybe i just dont know it.
Preferably one could define it on server level like below or as part of a route paramater

    const server = Hapi.server({
        port: 3000,
        host: 'localhost',
       base: "/api"
        routes: {
            files: {relativeTo: Path.join(__dirname, 'public')}
        }
    });

Thanks for your response

**Comment by DharanBro** [comment]
Hapi supports it while registering the plugin. So any routes that is being defined with plugin will have the mentioned prefix. Documented [here](https://hapi.dev/api/?v=19.2.0#-serverrealm) 
```
await server.register({
    plugin: restify,
    routes: { 'prefix': '/v1' },
    options: { sequelize },
});
```
